<a href="https://colab.research.google.com/github/rebeca07-pedrozo/P.L.N/blob/main/P_L_N.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [59]:
import numpy as np
import pandas as pd
import sympy as sp

# Ejericios sábado 9 de agosto

**Ejercicio  1**

**Ejericio 2**

In [13]:
A=np.array([2,-1,4,0,3])
B=np.array([-1,0,2,3,1])
C=np.array([0,1,-3,4,-7])
print(A,B,C)

[ 2 -1  4  0  3] [-1  0  2  3  1] [ 0  1 -3  4 -7]


In [14]:
operacion1=(2*A)-(3*B)+C
print(operacion1)

[ 7 -1 -1 -5 -4]


In [15]:
operacion2=np.dot(A,B)
print(operacion2)

9


In [16]:
operacion3=A*B
print(operacion3)


[-2  0  8  0  3]


**Ejercicio 3**




**Ejercicio 4**

In [55]:
matriz = np.random.randint(20, 40, size=(2,2))
print(matriz)

[[25 36]
 [25 24]]


In [56]:
determinante=np.linalg.det(matriz)
print(determinante)

-299.99999999999994


In [57]:
if determinante!=0:
  inversa= np.linalg.inv(matriz)
  print(inversa)
else:
  print("El determinante es 0")

[[-0.08        0.12      ]
 [ 0.08333333 -0.08333333]]


In [58]:
if determinante!=0:
  matrizIdentidad=np.dot(matriz,inversa)
  matrizIdentidad = np.round(matrizIdentidad, decimals=6)
  print("Matriz original por la inversa es:", matrizIdentidad)
else:
  print("La matriz no tiene inversa porque el determinante es cero")

Matriz original por la inversa es: [[ 1.  0.]
 [-0.  1.]]


In [65]:
MatrizSymPy = sp.Matrix(matriz)
letrica= sp.symbols('λ')

In [67]:
MatrizIdentidad = sp.eye(MatrizSymPy.shape[0])

In [68]:
polinomioCaracteristico = (MatrizSymPy - letrica * MatrizIdentidad).det()
print("polinomio Caracteristico:")
print(polinomioCaracteristico)

polinomio Caracteristico:
λ**2 - 49*λ - 300


**Ejericio 4**

**Ejercicio 5**

In [71]:
def f1(x):
  return np.sin(x**2)
x=1
print(f1(x))

0.8414709848078965


In [72]:
def g1(x):
  return np.sin(x)**2
x=1
print(g1(x))

0.7080734182735712


**Ejercicio 6**