<a href="https://colab.research.google.com/github/rebeca07-pedrozo/P.L.N/blob/main/P_L_N.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [30]:
import numpy as np
import pandas as pd
import sympy as sp

# Ejericios sábado 9 de agosto

**Ejercicio  1**

In [31]:
Logaritmo1=np.log(np.pi/4)
Logaritmo2=np.log(np.e**2)
print(Logaritmo2)
Seno=np.sin(np.pi/2)
print(Seno)
Arct=np.arctan(1)
print(Arct)
Log2=np.log2(10)


2.0
1.0
0.7853981633974483


In [32]:
print(np.log(np.pi/4))


-0.2415644752704905


In [33]:
print(np.log(np.e**2))

2.0


In [34]:
print(np.sin(np.pi/2))

1.0


In [35]:
print(np.arctan(1))

0.7853981633974483


In [36]:
print(np.log2(10))

3.321928094887362


**Ejericio 2**

In [37]:
A=np.array([2,-1,4,0,3])
B=np.array([-1,0,2,3,1])
C=np.array([0,1,-3,4,-7])
print(A,B,C)

[ 2 -1  4  0  3] [-1  0  2  3  1] [ 0  1 -3  4 -7]


In [38]:
operacion1=(2*A)-(3*B)+C
print(operacion1)

[ 7 -1 -1 -5 -4]


In [39]:
operacion2=np.dot(A,B)
print(operacion2)

9


In [40]:
operacion3=A*B
print(operacion3)


[-2  0  8  0  3]


**Ejercicio 3**




In [75]:
lista1=np.arange(2,22)
lista2=np.arange(22,32)
print(lista1)
print(lista2)

[ 2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21]
[22 23 24 25 26 27 28 29 30 31]


In [78]:
segundoElemento=lista1[1]
productos=segundoElemento*lista2
print(productos)

[66 69 72 75 78 81 84 87 90 93]


In [80]:
resultado=productos/lista2
print(resultado)

[3. 3. 3. 3. 3. 3. 3. 3. 3. 3.]


In [43]:
segundo_elem = lista1[1]
print("\nSegundo elemento de lista1:", segundo_elem)


Segundo elemento de lista1: 3


**Ejercicio 4**

In [46]:
matriz = np.random.randint(20, 40, size=(2,2))
print(matriz)

[[32 39]
 [39 28]]


In [47]:
determinante=np.linalg.det(matriz)
print(determinante)

-625.0000000000003


In [48]:
if determinante!=0:
  inversa= np.linalg.inv(matriz)
  print(inversa)
else:
  print("El determinante es 0")

[[-0.0448  0.0624]
 [ 0.0624 -0.0512]]


In [49]:
if determinante!=0:
  matrizIdentidad=np.dot(matriz,inversa)
  matrizIdentidad = np.round(matrizIdentidad, decimals=6)
  print("Matriz original por la inversa es:", matrizIdentidad)
else:
  print("La matriz no tiene inversa porque el determinante es cero")

Matriz original por la inversa es: [[ 1. -0.]
 [ 0.  1.]]


In [50]:
MatrizSymPy = sp.Matrix(matriz)
letrica= sp.symbols('λ')

In [51]:
MatrizIdentidad = sp.eye(MatrizSymPy.shape[0])

In [52]:
polinomioCaracteristico = (MatrizSymPy - letrica * MatrizIdentidad).det()
print("polinomio Caracteristico:")
print(polinomioCaracteristico)

polinomio Caracteristico:
λ**2 - 60*λ - 625


**Ejercicio 5**


In [65]:
x = sp.symbols('x')
z=(x+1)*(x-1)

In [66]:
elevado=(z**2)+(2*x)+2

In [68]:
simplificado = sp.simplify(elevado)


In [69]:
print(simplificado)

x**4 - 2*x**2 + 2*x + 3


**Ejercicio 6**

In [54]:
def f1(x):
  return np.sin(x**2)
x=1
print(f1(x))

0.8414709848078965


In [55]:
def g1(x):
  return np.sin(x)**2
x=1
print(g1(x))

0.7080734182735712
